name: Build-APK

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.2.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Export Android APK
        run: |
          mkdir -p build
          godot --headless -v --export-debug "Android" build/MKU_MAN.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MKU_MAN.apk
          path: build/MKU_MAN.apk
